import { Eye, EyeOff, LoaderCircle, LockKeyhole, Mail, UserRound } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import { Navigate } from 'react-router-dom'
import { useAuth } from '../lib/AuthContext'

export function AuthPage() {
  const { user, login, register } = useAuth(); const [mode,setMode]=useState<'login'|'register'>('login'); const [name,setName]=useState(''); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [show,setShow]=useState(false); const [error,setError]=useState(''); const [saving,setSaving]=useState(false)
  if (user) return <Navigate to="/" replace/>
  async function submit(event:FormEvent){event.preventDefault();setSaving(true);setError('');try{if(mode==='login')await login({email,password});else await register({name,email,password})}catch(err){setError(err instanceof Error?err.message:'Не удалось выполнить вход')}finally{setSaving(false)}}
  return <div className="auth-page"><div className="auth-card"><span className="auth-kicker">Личный планер</span><h1>{mode==='login'?'С возвращением':'Создайте профиль'}</h1><p>{mode==='login'?'Войдите, чтобы продолжить планирование.':'Все задачи, привычки и заметки будут связаны с вашим профилем.'}</p><div className="auth-tabs"><button className={mode==='login'?'active':''} onClick={()=>{setMode('login');setError('')}}>Вход</button><button className={mode==='register'?'active':''} onClick={()=>{setMode('register');setError('')}}>Регистрация</button></div><form onSubmit={submit}>{mode==='register'&&<label><span>Имя</span><div><UserRound/><input required minLength={2} maxLength={40} autoComplete="name" value={name} onChange={e=>setName(e.target.value)} placeholder="Как к вам обращаться"/></div></label>}<label><span>Email</span><div><Mail/><input required type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="name@example.com"/></div></label><label><span>Пароль</span><div><LockKeyhole/><input required minLength={8} maxLength={128} type={show?'text':'password'} autoComplete={mode==='login'?'current-password':'new-password'} value={password} onChange={e=>setPassword(e.target.value)} placeholder="Минимум 8 символов"/><button type="button" onClick={()=>setShow(!show)} aria-label="Показать пароль">{show?<EyeOff/>:<Eye/>}</button></div></label>{error&&<div className="auth-error">{error}</div>}<button className="primary auth-submit" disabled={saving}>{saving?<LoaderCircle className="spin"/>:null}{saving?'Подождите…':mode==='login'?'Войти':'Создать профиль'}</button></form><small>Ваши данные хранятся в личном профиле.</small></div></div>
}
