import { addMonths, eachDayOfInterval, endOfMonth, endOfWeek, format, isSameDay, isSameMonth, parseISO, startOfMonth, startOfWeek, subMonths } from 'date-fns'
import { ru } from 'date-fns/locale'
import { ChevronLeft, ChevronRight, Plus } from 'lucide-react'
import { useState } from 'react'
import { ConfirmModal, Empty, FormModal, Loading, PageHeader, Panel } from '../components/UI'
import { ItemActions } from '../components/ItemActions'
import { api } from '../lib/api'
import { useData } from '../lib/DataContext'
import { localDateTimeValue, toDateKey, toIso, todayKey } from '../lib/dates'
import type { CalendarEvent, Priority, Task } from '../types'

export function CalendarPage() {
  const {data,loading,mutate}=useData(); const [month,setMonth]=useState(new Date()); const [selected,setSelected]=useState(new Date()); const [mode,setMode]=useState<'event'|'task'|null>(null)
  const [event,setEvent]=useState<Partial<CalendarEvent>>({color:'#63e6d8'}); const [task,setTask]=useState<Partial<Task>>({priority:'medium'}); const [deleting,setDeleting]=useState<{kind:'tasks'|'calendars';id:string;name:string}|null>(null)
  if(loading)return <Loading/>; if(!data)return null
  const days=eachDayOfInterval({start:startOfWeek(startOfMonth(month),{weekStartsOn:1}),end:endOfWeek(endOfMonth(month),{weekStartsOn:1})}); const key=toDateKey(selected)
  const dayTasks=data.tasks.filter(item=>item.due_date===key); const dayEvents=data.events.filter(item=>toDateKey(item.starts_at)===key)
  const openEvent=(item?:CalendarEvent)=>{setEvent(item||{starts_at:`${key}T09:00`,ends_at:`${key}T10:00`,color:'#63e6d8'});setMode('event')}; const openTask=(item?:Task)=>{setTask(item||{due_date:key,priority:'medium'});setMode('task')}
  return <div className="page"><PageHeader eyebrow="Временная линия" title="Календарь" description="События и задачи в одном спокойном пространстве."/>
    <div className="calendar-layout"><Panel className="calendar-panel"><div className="calendar-nav"><button className="icon" onClick={()=>setMonth(subMonths(month,1))}><ChevronLeft/></button><h2>{format(month,'LLLL yyyy',{locale:ru})}</h2><button className="icon" onClick={()=>setMonth(addMonths(month,1))}><ChevronRight/></button></div><div className="week-labels">{['пн','вт','ср','чт','пт','сб','вс'].map(d=><span key={d}>{d}</span>)}</div><div className="calendar-grid">{days.map(day=>{const dayKey=toDateKey(day);const entries=data.tasks.filter(t=>t.due_date===dayKey).length+data.events.filter(e=>toDateKey(e.starts_at)===dayKey).length;return <button key={dayKey} className={`${!isSameMonth(day,month)?'muted':''} ${isSameDay(day,selected)?'selected':''} ${dayKey===todayKey()?'today':''}`} onClick={()=>setSelected(day)}><span>{format(day,'d')}</span>{entries>0&&<i>{entries}</i>}</button>})}</div></Panel>
      <Panel title={format(selected,'d MMMM, EEEE',{locale:ru})} subtitle={`${dayEvents.length+dayTasks.length} записей`} action={<div className="small-actions"><button className="icon" onClick={()=>openEvent()} title="Событие"><Plus/></button></div>}><div className="day-actions"><button onClick={()=>openEvent()} className="secondary"><Plus size={16}/> Событие</button><button onClick={()=>openTask()} className="secondary"><Plus size={16}/> Задача</button></div><h3 className="section-label">События</h3><div className="day-list">{dayEvents.length?dayEvents.map(item=><article key={item.id}><i style={{background:item.color}}/><div><strong>{item.title}</strong><span>{format(parseISO(item.starts_at),'HH:mm')} {item.ends_at?`— ${format(parseISO(item.ends_at),'HH:mm')}`:''}</span></div><ItemActions onEdit={()=>openEvent(item)} onDelete={()=>setDeleting({kind:'calendars',id:item.id,name:item.title})}/></article>):<Empty text="Событий нет"/>}</div><h3 className="section-label">Задачи</h3><div className="day-list">{dayTasks.length?dayTasks.map(item=><article key={item.id}><i className={`task-dot ${item.priority}`}/><div><strong>{item.title}</strong><span>{item.completed?'Выполнена':'Ждёт выполнения'}</span></div><ItemActions onEdit={()=>openTask(item)} onDelete={()=>setDeleting({kind:'tasks',id:item.id,name:item.title})}/></article>):<Empty text="Задач нет"/>}</div></Panel>
    </div>
    <FormModal open={mode==='event'} title={event.id?'Редактировать событие':'Новое событие'} onClose={()=>setMode(null)} onSubmit={()=>mutate(()=>event.id?api.update('events',event.id,{title:event.title,starts_at:toIso(event.starts_at!),ends_at:event.ends_at?toIso(event.ends_at):null,color:event.color}):api.create('events',{title:event.title,starts_at:toIso(event.starts_at!),ends_at:event.ends_at?toIso(event.ends_at):null,color:event.color}),'Событие сохранено')}><label>Название<input required value={event.title||''} onChange={e=>setEvent({...event,title:e.target.value})}/></label><div className="form-grid"><label>Начало<input type="datetime-local" required value={localDateTimeValue(event.starts_at)} onChange={e=>setEvent({...event,starts_at:e.target.value})}/></label><label>Окончание<input type="datetime-local" value={event.ends_at?localDateTimeValue(event.ends_at):''} onChange={e=>setEvent({...event,ends_at:e.target.value})}/></label></div><label>Цвет<input className="color-input" type="color" value={event.color||'#63e6d8'} onChange={e=>setEvent({...event,color:e.target.value})}/></label></FormModal>
    <FormModal open={mode==='task'} title={task.id?'Редактировать задачу':'Новая задача'} onClose={()=>setMode(null)} onSubmit={()=>mutate(()=>task.id?api.update('tasks',task.id,{title:task.title,due_date:task.due_date,priority:task.priority}):api.create('tasks',{title:task.title,due_date:task.due_date,priority:task.priority}),'Задача сохранена')}><label>Название<input required value={task.title||''} onChange={e=>setTask({...task,title:e.target.value})}/></label><div className="form-grid"><label>Дата<input type="date" required value={task.due_date||key} onChange={e=>setTask({...task,due_date:e.target.value})}/></label><label>Приоритет<select value={task.priority} onChange={e=>setTask({...task,priority:e.target.value as Priority})}><option value="low">Низкий</option><option value="medium">Средний</option><option value="high">Высокий</option></select></label></div></FormModal>
    <ConfirmModal open={!!deleting} name={deleting?.name||''} onClose={()=>setDeleting(null)} onConfirm={()=>mutate(()=>api.remove(deleting!.kind,deleting!.id),'Запись удалена')}/>
  </div>
}
