import { Check, Circle, Clock3, MapPin, Plus } from 'lucide-react'
import { useState } from 'react'
import { ConfirmModal, Empty, FormModal, Loading, Modal, PageHeader, Panel } from '../components/UI'
import { ItemActions } from '../components/ItemActions'
import { api } from '../lib/api'
import { useData } from '../lib/DataContext'
import { formatDateTime, lastSevenDays, localDateTimeValue, toDateKey, toIso, todayKey } from '../lib/dates'
import type { Habit, Note, Plan, Reminder, Schedule } from '../types'

const weekdays=['Понедельник','Вторник','Среда','Четверг','Пятница','Суббота','Воскресенье']
type DeleteState={kind:'reminders'|'schedule'|'habits'|'plans'|'notes';id:string;name:string}|null

export function RemindersPage(){
  const{data,loading,mutate}=useData();const[open,setOpen]=useState(false);const[item,setItem]=useState<Partial<Reminder>>({});const[del,setDel]=useState<DeleteState>(null)
  if(loading)return <Loading/>;if(!data)return null;const items=[...data.reminders].sort((a,b)=>a.remind_at.localeCompare(b.remind_at));const edit=(value?:Reminder)=>{setItem(value||{remind_at:`${todayKey()}T09:00`});setOpen(true)}
  return <div className="page"><PageHeader eyebrow="Не забыть" title="Напоминания" description="Важные сигналы в нужный момент." action={()=>edit()}/><Panel><div className="cards-list">{items.length?items.map(value=>{const late=!value.completed&&new Date(value.remind_at)<new Date();return <article className={`reminder-card ${late?'overdue':''} ${value.completed?'complete':''}`} key={value.id}><button className="check" onClick={()=>void mutate(()=>api.toggle('reminders',value.id),value.completed?'Напоминание возвращено':'Готово')}>{value.completed?<Check/>:<Circle/>}</button><div><strong>{value.title}</strong><span><Clock3 size={14}/>{formatDateTime(value.remind_at)}{late&&<b>просрочено</b>}</span></div><ItemActions onEdit={()=>edit(value)} onDelete={()=>setDel({kind:'reminders',id:value.id,name:value.title})}/></article>}):<Empty text="Напоминаний пока нет"/>}</div></Panel><FormModal open={open} title={item.id?'Изменить напоминание':'Новое напоминание'} onClose={()=>setOpen(false)} onSubmit={()=>mutate(()=>item.id?api.update('reminders',item.id,{title:item.title,remind_at:toIso(item.remind_at!)}):api.create('reminders',{title:item.title,remind_at:toIso(item.remind_at!)}),'Напоминание сохранено')}><label>О чём напомнить<input required autoFocus value={item.title||''} onChange={e=>setItem({...item,title:e.target.value})}/></label><label>Дата и время<input type="datetime-local" required value={localDateTimeValue(item.remind_at)} onChange={e=>setItem({...item,remind_at:e.target.value})}/></label></FormModal><DeleteConfirm state={del} setState={setDel}/></div>
}

export function SchedulePage(){
  const{data,loading,mutate}=useData();const[open,setOpen]=useState(false);const[item,setItem]=useState<Partial<Schedule>>({week_number:1,weekday:0,starts_at:'09:00',ends_at:'10:30'});const[del,setDel]=useState<DeleteState>(null)
  if(loading)return <Loading/>;if(!data)return null
  const edit=(value?:Schedule)=>{setItem(value||{week_number:1,weekday:0,starts_at:'09:00',ends_at:'10:30',location:''});setOpen(true)}
  const renderWeek=(weekNumber:1|2,label:string)=><section className="schedule-week"><header className="schedule-week-title"><div><span className="eyebrow">Постоянный шаблон</span><h2>{label}</h2></div><small>Понедельник — воскресенье</small></header><div className="week-board">{weekdays.map((day,index)=>{const entries=data.schedule.filter(s=>s.week_number===weekNumber&&s.weekday===index);return <section key={`${weekNumber}-${day}`}><header><span>{day.slice(0,2)}</span><strong>{day}</strong></header><div>{entries.map(value=><article key={value.id}><time>{value.starts_at.slice(0,5)} — {value.ends_at.slice(0,5)}</time><strong>{value.title}</strong><span><MapPin size={13}/>{value.location||'Место не указано'}</span><ItemActions onEdit={()=>edit(value)} onDelete={()=>setDel({kind:'schedule',id:value.id,name:value.title})}/></article>)}{!entries.length&&<button className="add-slot" onClick={()=>{setItem({week_number:weekNumber,weekday:index,starts_at:'09:00',ends_at:'10:30',location:''});setOpen(true)}}><Plus/> Добавить</button>}</div></section>})}</div></section>
  const payload={title:item.title,week_number:item.week_number,weekday:item.weekday,starts_at:item.starts_at,ends_at:item.ends_at,location:item.location||null}
  return <div className="page"><PageHeader eyebrow="Две недели" title="Расписание" description="Два независимых расписания с понедельника по воскресенье. Записи сохраняются и не меняются при наступлении новой недели." action={()=>edit()}/><div className="schedule-weeks">{renderWeek(1,'Первая неделя')}{renderWeek(2,'Вторая неделя')}</div><FormModal open={open} title={item.id?'Редактировать занятие':'Новое занятие'} onClose={()=>setOpen(false)} onSubmit={()=>mutate(()=>item.id?api.update('schedule',item.id,payload):api.create('schedule',payload),'Расписание обновлено')}><label>Название<input required value={item.title||''} onChange={e=>setItem({...item,title:e.target.value})}/></label><div className="form-grid"><label>Неделя<select value={item.week_number||1} onChange={e=>setItem({...item,week_number:Number(e.target.value) as 1|2})}><option value={1}>Первая неделя</option><option value={2}>Вторая неделя</option></select></label><label>День<select value={item.weekday} onChange={e=>setItem({...item,weekday:Number(e.target.value)})}>{weekdays.map((d,i)=><option key={d} value={i}>{d}</option>)}</select></label><label>Аудитория / место<input maxLength={120} value={item.location||''} onChange={e=>setItem({...item,location:e.target.value})}/></label><label>Начало<input type="time" required value={item.starts_at?.slice(0,5)||''} onChange={e=>setItem({...item,starts_at:e.target.value})}/></label><label>Окончание<input type="time" required value={item.ends_at?.slice(0,5)||''} onChange={e=>setItem({...item,ends_at:e.target.value})}/></label></div></FormModal><DeleteConfirm state={del} setState={setDel}/></div>
}

export function HabitsPage(){
  const{data,loading,mutate}=useData();const[open,setOpen]=useState(false);const[item,setItem]=useState<Partial<Habit>>({color:'#63e6d8'});const[del,setDel]=useState<DeleteState>(null);const days=lastSevenDays()
  if(loading)return <Loading/>;if(!data)return null;const edit=(value?:Habit)=>{setItem(value||{color:'#63e6d8'});setOpen(true)}
  return <div className="page"><PageHeader eyebrow="Каждый день" title="Трекер привычек" description="Семь дней маленьких, но заметных побед." action={()=>edit()}/><Panel><div className="habit-table"><div className="habit-head"><span>Привычка</span>{days.map(d=><span key={toDateKey(d)}>{d.toLocaleDateString('ru',{weekday:'short'})}<b>{d.getDate()}</b></span>)}<span/></div>{data.habits.length?data.habits.map(value=><div className="habit-row" key={value.id}><strong><i style={{background:value.color}}/>{value.title}</strong>{days.map(day=>{const key=toDateKey(day),checked=value.checked_days.includes(key);return <button key={key} className={checked?'checked':''} style={checked?{background:value.color}:undefined} onClick={()=>void mutate(()=>api.checkin(value.id,key),checked?'Отметка снята':'Отличный ритм!')}>{checked?<Check size={17}/>:null}</button>})}<ItemActions onEdit={()=>edit(value)} onDelete={()=>setDel({kind:'habits',id:value.id,name:value.title})}/></div>):<Empty text="Добавьте первую привычку"/>}</div></Panel><FormModal open={open} title={item.id?'Изменить привычку':'Новая привычка'} onClose={()=>setOpen(false)} onSubmit={()=>mutate(()=>item.id?api.update('habits',item.id,{title:item.title,color:item.color}):api.create('habits',{title:item.title,color:item.color}),'Привычка сохранена')}><label>Название<input required maxLength={120} value={item.title||''} onChange={e=>setItem({...item,title:e.target.value})}/></label><label>Цвет<input className="color-input" type="color" value={item.color||'#63e6d8'} onChange={e=>setItem({...item,color:e.target.value})}/></label></FormModal><DeleteConfirm state={del} setState={setDel}/></div>
}

export function PlansPage(){
  const{data,loading,mutate}=useData();const[open,setOpen]=useState(false);const[item,setItem]=useState<Partial<Plan>>({});const[del,setDel]=useState<DeleteState>(null);if(loading)return <Loading/>;if(!data)return null;const edit=(value?:Plan)=>{setItem(value||{});setOpen(true)}
  return <div className="page"><PageHeader eyebrow="Большая картина" title="Планы" description="Идеи, которые постепенно становятся реальностью." action={()=>edit()}/><div className="card-grid">{data.plans.length?data.plans.map(value=><article className={`plan-card ${value.completed?'complete':''}`} key={value.id}><button className="check" onClick={()=>void mutate(()=>api.toggle('plans',value.id),value.completed?'План снова активен':'План завершён')}>{value.completed?<Check/>:<Circle/>}</button><div><span className="eyebrow">{value.completed?'Завершено':'В планах'}</span><h2>{value.title}</h2><p>{value.description||'Описание пока не добавлено.'}</p></div><ItemActions onEdit={()=>edit(value)} onDelete={()=>setDel({kind:'plans',id:value.id,name:value.title})}/></article>):<Empty text="Создайте первый большой план"/>}</div><FormModal open={open} title={item.id?'Редактировать план':'Новый план'} onClose={()=>setOpen(false)} onSubmit={()=>mutate(()=>item.id?api.update('plans',item.id,{title:item.title,description:item.description||''}):api.create('plans',{title:item.title,description:item.description||''}),'План сохранён')}><label>Название<input required value={item.title||''} onChange={e=>setItem({...item,title:e.target.value})}/></label><label>Описание<textarea rows={6} maxLength={4000} value={item.description||''} onChange={e=>setItem({...item,description:e.target.value})}/></label></FormModal><DeleteConfirm state={del} setState={setDel}/></div>
}

export function NotesPage(){
  const{data,loading,mutate}=useData();const[open,setOpen]=useState(false);const[item,setItem]=useState<Partial<Note>>({});const[view,setView]=useState<Note|null>(null);const[del,setDel]=useState<DeleteState>(null);if(loading)return <Loading/>;if(!data)return null;const edit=(value?:Note)=>{setView(null);setItem(value||{});setOpen(true)}
  return <div className="page"><PageHeader eyebrow="Мысли на полях" title="Заметки" description="Место для идей, наблюдений и случайных созвездий." action={()=>edit()}/><div className="notes-grid">{data.notes.length?data.notes.map(value=><article className="note-card" key={value.id} onClick={()=>setView(value)}><span>{formatDateTime(value.updated_at)}</span><h2>{value.title}</h2><p>{value.content||'Пустая заметка'}</p><ItemActions onEdit={()=>edit(value)} onDelete={()=>setDel({kind:'notes',id:value.id,name:value.title})}/></article>):<Empty text="Запишите первую мысль"/>}</div><FormModal open={open} title={item.id?'Редактировать заметку':'Новая заметка'} onClose={()=>setOpen(false)} onSubmit={()=>mutate(()=>item.id?api.update('notes',item.id,{title:item.title,content:item.content||''}):api.create('notes',{title:item.title,content:item.content||''}),'Заметка сохранена')}><label>Заголовок<input required value={item.title||''} onChange={e=>setItem({...item,title:e.target.value})}/></label><label>Текст<textarea rows={10} maxLength={20000} value={item.content||''} onChange={e=>setItem({...item,content:e.target.value})}/></label></FormModal><Modal open={!!view} title={view?.title||''} onClose={()=>setView(null)}><div className="note-full">{view?.content||'Пустая заметка'}</div><div className="modal-actions"><button className="secondary" onClick={()=>edit(view!)}>Редактировать</button></div></Modal><DeleteConfirm state={del} setState={setDel}/></div>
}

export function SettingsPage(){return <div className="page"><PageHeader eyebrow="Параметры" title="Настройки" description="Внешний вид и локальные параметры планера."/><div className="settings-grid"><Panel title="Внешний вид"><label className="setting-row"><span><strong>Небесно-голубая тема</strong><small>Основная тема приложения</small></span><input type="checkbox" checked readOnly/></label><label className="setting-row"><span><strong>Мягкие анимации</strong><small>Переходы и состояния интерфейса</small></span><input type="checkbox" defaultChecked/></label></Panel><Panel title="Локальные параметры"><div className="setting-row"><span><strong>Язык</strong><small>Язык интерфейса</small></span><b>Русский</b></div><div className="setting-row"><span><strong>Часовой пояс</strong><small>Определяется браузером</small></span><b>{Intl.DateTimeFormat().resolvedOptions().timeZone}</b></div></Panel></div></div>}

function DeleteConfirm({state,setState}:{state:DeleteState;setState:(value:DeleteState)=>void}){const{mutate}=useData();return <ConfirmModal open={!!state} name={state?.name||''} onClose={()=>setState(null)} onConfirm={()=>mutate(()=>api.remove(state!.kind,state!.id),'Запись удалена')}/>}
