import { Check, Circle, Target } from 'lucide-react'
import { useState } from 'react'
import { ConfirmModal, Empty, FormModal, Loading, PageHeader, Panel } from '../components/UI'
import { ItemActions } from '../components/ItemActions'
import { api } from '../lib/api'
import { useData } from '../lib/DataContext'
import { formatDate, todayKey, weekStartKey } from '../lib/dates'
import type { Goal, Priority, Task } from '../types'

export function TasksGoalsPage() {
  const { data, loading, mutate } = useData(); const [tab, setTab] = useState<'today'|'all'>('today'); const [taskOpen, setTaskOpen] = useState(false); const [goalOpen, setGoalOpen] = useState(false)
  const [task, setTask] = useState<Partial<Task>>({ priority: 'medium', due_date: todayKey() }); const [goal, setGoal] = useState<Partial<Goal>>({ week_start: weekStartKey(), progress: 0 }); const [deleting, setDeleting] = useState<{kind:'tasks'|'goals'; id:string; name:string}|null>(null)
  if (loading) return <Loading/>; if (!data) return null
  const tasks = tab === 'today' ? data.tasks.filter(item => item.due_date === todayKey()) : data.tasks
  const editTask = (item?: Task) => { setTask(item || { priority:'medium', due_date:todayKey() }); setTaskOpen(true) }
  const editGoal = (item?: Goal) => { setGoal(item || { week_start:weekStartKey(), progress:0 }); setGoalOpen(true) }
  const saveTask = () => mutate(() => task.id ? api.update('tasks', task.id, { title:task.title, due_date:task.due_date || null, priority:task.priority }) : api.create('tasks', { title:task.title, due_date:task.due_date || null, priority:task.priority }), 'Задача сохранена')
  const saveGoal = async () => { const ok = await mutate(() => goal.id ? api.update('goals', goal.id, { title:goal.title, week_start:goal.week_start }) : api.create<Goal>('goals', { title:goal.title, week_start:goal.week_start }).then(created => goal.progress ? api.progress(created.id, goal.progress) : created), 'Цель сохранена'); if (ok && goal.id && goal.progress !== undefined) await mutate(() => api.progress(goal.id!, goal.progress!), 'Прогресс обновлён'); return ok }
  return <div className="page"><PageHeader eyebrow="Фокус" title="Задачи и цели" description="Соберите ясный план и отмечайте движение к главному." action={() => editTask()}/>
    <div className="toolbar"><div className="segmented"><button className={tab==='today'?'active':''} onClick={()=>setTab('today')}>Сегодня</button><button className={tab==='all'?'active':''} onClick={()=>setTab('all')}>Все задачи</button></div><button className="secondary" onClick={()=>editGoal()}><Target size={17}/> Новая цель</button></div>
    <div className="tasks-layout"><Panel title={tab==='today'?'Сегодняшний план':'Все задачи'} subtitle={`${tasks.filter(t=>t.completed).length} из ${tasks.length} выполнено`} className="span-2">
      <div className="task-list">{tasks.length ? tasks.map(item => <article className={`task-item ${item.completed?'complete':''}`} key={item.id}><button className="check" onClick={()=>void mutate(()=>api.toggle('tasks',item.id), item.completed?'Задача возвращена':'Задача выполнена')}>{item.completed?<Check/>:<Circle/>}</button><div className="task-main"><strong>{item.title}</strong><span>{item.due_date ? formatDate(item.due_date) : 'Без даты'} · <i className={`priority ${item.priority}`}>{item.priority==='high'?'высокий':item.priority==='low'?'низкий':'средний'}</i></span></div><ItemActions onEdit={()=>editTask(item)} onDelete={()=>setDeleting({kind:'tasks',id:item.id,name:item.title})}/></article>) : <Empty text="Здесь пока тихо — добавьте задачу"/>}</div>
    </Panel><Panel title="Главные цели недели" subtitle="Плавно регулируйте прогресс"><div className="weekly-goals">{data.goals.length ? data.goals.map(item => <article key={item.id}><div className="goal-title"><div><strong>{item.title}</strong><span>Неделя от {formatDate(item.week_start)}</span></div><ItemActions onEdit={()=>editGoal(item)} onDelete={()=>setDeleting({kind:'goals',id:item.id,name:item.title})}/></div><div className="range-row"><input type="range" min="0" max="100" value={item.progress} onChange={e=>void mutate(()=>api.progress(item.id,Number(e.target.value)),'Прогресс обновлён')}/><b>{item.progress}%</b></div></article>) : <Empty text="Целей на неделю пока нет"/>}</div></Panel></div>
    <FormModal open={taskOpen} title={task.id?'Редактировать задачу':'Новая задача'} onClose={()=>setTaskOpen(false)} onSubmit={saveTask}><label>Название<input required maxLength={180} autoFocus value={task.title||''} onChange={e=>setTask({...task,title:e.target.value})}/></label><div className="form-grid"><label>Дата<input type="date" value={task.due_date||''} onChange={e=>setTask({...task,due_date:e.target.value})}/></label><label>Приоритет<select value={task.priority} onChange={e=>setTask({...task,priority:e.target.value as Priority})}><option value="low">Низкий</option><option value="medium">Средний</option><option value="high">Высокий</option></select></label></div></FormModal>
    <FormModal open={goalOpen} title={goal.id?'Редактировать цель':'Новая цель'} onClose={()=>setGoalOpen(false)} onSubmit={saveGoal}><label>Цель<input required maxLength={180} autoFocus value={goal.title||''} onChange={e=>setGoal({...goal,title:e.target.value})}/></label><label>Начало недели<input type="date" required value={goal.week_start||''} onChange={e=>setGoal({...goal,week_start:e.target.value})}/></label>{goal.id&&<label>Прогресс — {goal.progress}%<input type="range" min="0" max="100" value={goal.progress||0} onChange={e=>setGoal({...goal,progress:Number(e.target.value)})}/></label>}</FormModal>
    <ConfirmModal open={!!deleting} name={deleting?.name||''} onClose={()=>setDeleting(null)} onConfirm={()=>mutate(()=>api.remove(deleting!.kind,deleting!.id),'Запись удалена')}/>
  </div>
}
